### ISSUE TITLE
大佬，请问显示不出界面怎么办

### ISSUE THREAD

**Issue by catabridge** [emtry/Bing-Auto-Search#1]
![image](https://user-images.githubusercontent.com/98137817/150465852-a3bb7c7f-9806-4dc4-8316-f4261fbc0d91.png)
kan'd'd看到的界面是这样的

**Comment by curiositah** [comment]
地区不可用要怎么办？改账户地区还是节点（这俩个都试过但没什么用），还是其他

**Comment by catabridge** [comment]
> 地区不可用要怎么办？改账户地区还是节点（这俩个都试过但没什么用），还是其他

需要用它界面上对应需要的区域节点

**Comment by emtry** [comment]
美区节点即可，不用改账户地区

catabridge ***@***.***> 于2022年1月22日周六 17:50写道：

**Comment by emtry** [comment]
closed
