### ISSUE TITLE
国区已经可以正常访问了，不需要代理了，但是无法运行，提示用户未登录

### ISSUE THREAD

**Issue by oldye2020** [emtry/Bing-Auto-Search#11]
我是青龙面板运行
![image](https://user-images.githubusercontent.com/68853136/203086976-9a3200b1-53b1-4dfe-b85b-6f6070f7295f.png)

**Comment by emtry** [comment]
国区为cn.bing.com，脚本判断www.bing.com，暂未支持，下个版本更新吧

**Comment by emtry** [comment]
指定 axios@1.1.3

**Comment by x1737886903** [comment]
> 指定 axios@1.1.3

我现在指定了 axios@1.1.3，没开代理，还是提示“未获取到登录信息”

**Comment by emtry** [comment]
暂未支持国区

**Comment by emtry** [comment]
油猴脚本
https://github.com/emtry/Bing-Auto-Search/raw/main/Bing%20Auto%20Search%20CN.user.js
