### ISSUE TITLE
昨天用青龙更新了脚本，不知道什么引起的，所有cookie全部失效，无论怎么重新获取，都显示未登录

### ISSUE THREAD

**Issue by Plus-xu** [emtry/Bing-Auto-Search#12]
版本
2.0.5
用的bing.com的cookie 然后加‘;' 再加rewards.bing.com的cookie

**Comment by BigYty** [comment]
今天更新脚本后，即使使用了新的ck也提示未登录

**Comment by Plus-xu** [comment]
> 今天更新脚本后，即使使用了新的ck也提示未登录

不知道是脚本失效了还是什么原因，更新ck也全部显示未登录

**Comment by emtry** [comment]
用梯子获取cookie试试

**Comment by BigYty** [comment]
是用梯子获取的ck，以及按照他人的获取bing.com的ck并';'同reward的ck放一起也失败了

**Comment by emtry** [comment]
我测试正常呀，脚本有挂到代理吗

**Comment by Plus-xu** [comment]
脚本的代理是不是有什么bug？我路由有clash，青龙自动翻墙，不需要填脚本的代理，之前都正常的，我更新了一下就全是未登录了

**Comment by BigYty** [comment]
我的服务器在美国，不需要使用代理吧，可依然失败!

**Comment by emtry** [comment]
67行改成 console.log(response.data); 看看输出有没有自己的用户名，
没有的话单独放www.bing.com的cookie试试

**Comment by BigYty** [comment]
我将第67行的process.exit()更改成为console.log(response.data)后，输出日志如下
![Screenshot_2022-11-30-21-57-25-787_com microsoft emmx](https://user-images.githubusercontent.com/35890111/204814993-ef383874-67c2-4e6f-bf68-745f1a6fecf9.jpg)

**Comment by BigYty** [comment]
当我将process.exit()更改为console.log（response.data）后，日志输出如图所示
![IMG_20221130_215856](https://user-images.githubusercontent.com/35890111/204815393-1dcfefcd-1b3e-40c8-978f-9fd705b67b3f.jpg)

**Comment by WZ-Fate** [comment]
![QQ截图20221130234715](https://user-images.githubusercontent.com/78136384/204843982-21115c19-4c84-474a-acb3-4f28817e1ad2.png)
67行改了后放rewards.bing.com的cookie，貌似真的跑起来了...

**Comment by emtry** [comment]
> 当我将process.exit()更改为console.log（response.data）后，日志输出如图所示
> ![IMG_20221130_215856](https://user-images.githubusercontent.com/35890111/204815393-1dcfefcd-1b3e-40c8-978f-9fd705b67b3f.jpg)

404了，可能是网络问题吧

**Comment by emtry** [comment]
> ![QQ截图20221130234715](https://user-images.githubusercontent.com/78136384/204843982-21115c19-4c84-474a-acb3-4f28817e1ad2.png)
> 67行改了后放rewards.bing.com的cookie，貌似真的跑起来了...

错误：username is not defined
没获取到你的用户名，所以提示未登录，之前67行判断没获取到你的用户名就退出了，原因不明

**Comment by Plus-xu** [comment]
> > ![QQ截图20221130234715](https://user-images.githubusercontent.com/78136384/204843982-21115c19-4c84-474a-acb3-4f28817e1ad2.png)
> > 67行改了后放rewards.bing.com的cookie，貌似真的跑起来了...
> 
> 错误：username is not defined 没获取到你的用户名，所以提示未登录，之前67行判断没获取到你的用户名就退出了，原因不明

我和他一样，改了67行以后

ReferenceError: username is not defined
    at /ql/scripts/raw_main_Bing-Auto-Search_2.js:89:63
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by emtry** [comment]
WeChat?

**Comment by BigYty** [comment]
问题今天解决了，用美国的ip登录后，脚本运行起来了，但似乎只能完成日常的搜索任务。并且我的多个账户无法全部识别，只能识别最后一个添加的账户ck

**Comment by Plus-xu** [comment]
今天试了下刚更新的新版本，没有乱码，可以运行，不过还是检测不到账号信息，TG的通知看不到
![image](https://user-images.githubusercontent.com/52371609/205213122-4145dbed-223e-4bfa-8c26-1b3bf438cf45.png)

**Comment by emtry** [comment]
> 问题今天解决了，用美国的ip登录后，脚本运行起来了，但似乎只能完成日常的搜索任务。并且我的多个账户无法全部识别，只能识别最后一个添加的账户ck

没有适配多账户，建议一个账户一个脚本，分开时间运行

**Comment by emtry** [comment]
> 今天试了下刚更新的新版本，没有乱码，可以运行，不过还是检测不到账号信息，TG的通知看不到
> ![image](https://user-images.githubusercontent.com/52371609/205213122-4145dbed-223e-4bfa-8c26-1b3bf438cf45.png)

检测不到账号信息是cookie问题，先登录 http://www.bing.com/，再在同一标签页打开 http://rewards.bing.com/

TG推送测试正常

**Comment by emtry** [comment]
指定 axios@1.1.3

**Comment by Plus-xu** [comment]
> 指定 axios@1.1.3

牛的，终于能识别了
