### ISSUE TITLE
国内还是无法使用登陆

### ISSUE THREAD

**Issue by oldye2020** [emtry/Bing-Auto-Search#14]
![image](https://user-images.githubusercontent.com/68853136/206460078-1ca26881-9e39-4bfa-ba35-39780bd9a8db.png)

**Comment by emtry** [comment]
国内目前测试不加分，还没搞

**Comment by emtry** [comment]
油猴脚本
https://github.com/emtry/Bing-Auto-Search/raw/main/Bing%20Auto%20Search%20CN.user.js
