### ISSUE TITLE
更新Cookie后，目前已无法获取网页和电脑搜索分数

### ISSUE THREAD

**Issue by Plus-xu** [emtry/Bing-Auto-Search#15]
更新CK以后，只有手机搜索的分数可以正常获取，而网页和电脑搜索的分数无法获取
环境：
青龙
Bing-Auto-Search 2.1.1 最新版
通过Brave和Chrome 隐私模式获取CK
axios@1.1.3

**Comment by emtry** [comment]
换个节点试试或者换个UA试试吧

**Comment by Darkware-2019** [comment]
同问题，环境：青龙v2.15.5
Bing-Auto-Search 2.1.1最新版
通过Edge模式获取CK，确认可以刷电脑端搜索，和Edge分数，手机搜索分数没法做
依赖如md文档

**Comment by Darkware-2019** [comment]
没事了，今天重新抓了一次CK，恢复正常了
