### ISSUE TITLE
一直显示未获取登录信息

### ISSUE THREAD

**Issue by pino889** [emtry/Bing-Auto-Search#16]
ck填了，一直报错

Bing Auto Search
Version 2.3.2

未获取到登录信息

AxiosError: Request failed with status code 500
AxiosError: Request failed with status code 500
AxiosError: Request failed with status code 500
AxiosError: Request failed with status code 500
AxiosError: Request failed with status code 500
AxiosError: Request failed with status code 500
AxiosError: Request failed with status code 500
AxiosError: Request failed with status code 500

登录失败

**Comment by emtry** [comment]
梯子挂了吗

**Comment by pino889** [comment]
您好，您的邮件我已经收到，我会尽快给您回复！祝工作顺利，心情愉快，谢谢！

**Comment by sanzo-mlgb** [comment]
> 梯子挂了吗

在aws日本和国内联通网络，试过直接运行和青龙，均提示500

## 开始执行... 2023-01-29 09:45:17


Bing Auto Search
Version 2.3.4

已登录账号: xxxxxx@xxxxx.com

AxiosError: Request failed with status code 500
AxiosError: Request failed with status code 500
AxiosError: Request failed with status code 500
AxiosError: Request failed with status code 500
AxiosError: Request failed with status code 500
AxiosError: Request failed with status code 500
AxiosError: Request failed with status code 500
AxiosError: Request failed with status code 500

登录失败，请尝试重新获取cookie


## 执行结束... 2023-01-29 09:45:26 耗时 9 秒

此脚本对账号等级有需求吗？目前账号是1级

**Comment by pino889** [comment]
> > 梯子挂了吗
> 
> 在aws日本和国内联通网络，试过直接运行和青龙，均提示500
> 
> ## 开始执行... 2023-01-29 09:45:17
> Bing Auto Search Version 2.3.4
> 
> 已登录账号: [xxxxxx@xxxxx.com](mailto:xxxxxx@xxxxx.com)
> 
> AxiosError: Request failed with status code 500 AxiosError: Request failed with status code 500 AxiosError: Request failed with status code 500 AxiosError: Request failed with status code 500 AxiosError: Request failed with status code 500 AxiosError: Request failed with status code 500 AxiosError: Request failed with status code 500 AxiosError: Request failed with status code 500
> 
> 登录失败，请尝试重新获取cookie
> 
> ## 执行结束... 2023-01-29 09:45:26 耗时 9 秒
> 此脚本对账号等级有需求吗？目前账号是1级

目前也和你一样的问题，能登陆但是报错500

**Comment by emtry** [comment]
> > 梯子挂了吗
> 
> 在aws日本和国内联通网络，试过直接运行和青龙，均提示500
> 
> ## 开始执行... 2023-01-29 09:45:17
> Bing Auto Search Version 2.3.4
> 
> 已登录账号: [xxxxxx@xxxxx.com](mailto:xxxxxx@xxxxx.com)
> 
> AxiosError: Request failed with status code 500 AxiosError: Request failed with status code 500 AxiosError: Request failed with status code 500 AxiosError: Request failed with status code 500 AxiosError: Request failed with status code 500 AxiosError: Request failed with status code 500 AxiosError: Request failed with status code 500 AxiosError: Request failed with status code 500
> 
> 登录失败，请尝试重新获取cookie
> 
> ## 执行结束... 2023-01-29 09:45:26 耗时 9 秒
> 此脚本对账号等级有需求吗？目前账号是1级

没有要求呀，美国梯子测试正常使用

**Comment by freysu** [comment]
把`https://rewards.bing.com/api/getuserinfo/`替换成`https://rewards.bing.com/api/getuserinfo?type=1` 就可以用了

**Comment by pino889** [comment]
> https://rewards.bing.com/api/getuserinfo?type=1

改了之后可以获取当前积分了，但是报这个错
TypeError: Cannot read properties of undefined (reading '0')

**Comment by emtry** [comment]
> > https://rewards.bing.com/api/getuserinfo?type=1
> 
> 改了之后可以获取当前积分了，但是报这个错 TypeError: Cannot read properties of undefined (reading '0')

没有rewards的cookie

**Comment by sanzo-mlgb** [comment]
> https://rewards.bing.com/api/getuserinfo?type=1
改了之后可以正常使用了

**Comment by freysu** [comment]
> > https://rewards.bing.com/api/getuserinfo?type=1
> 
> 改了之后可以获取当前积分了，但是报这个错 TypeError: Cannot read properties of undefined (reading '0')

试试把`response.data.dashboard.userStatus.counters.shopAndEarn[0]`改成`response.data.dashboard.userStatus.counters.pcSearch[0]`，或者你重新获取一遍完整的cookie试试

**Comment by emtry** [comment]
> > > https://rewards.bing.com/api/getuserinfo?type=1
> > 
> > 
> > 改了之后可以获取当前积分了，但是报这个错 TypeError: Cannot read properties of undefined (reading '0')
> 
> 试试把`response.data.dashboard.userStatus.counters.shopAndEarn[0]`改成`response.data.dashboard.userStatus.counters.pcSearch[0]`，或者你重新获取一遍完整的cookie试试

2.4.0已更新这里

**Comment by pino889** [comment]
> > > https://rewards.bing.com/api/getuserinfo?type=1
> > 
> > 
> > 改了之后可以获取当前积分了，但是报这个错 TypeError: Cannot read properties of undefined (reading '0')
> 
> 试试把`response.data.dashboard.userStatus.counters.shopAndEarn[0]`改成`response.data.dashboard.userStatus.counters.pcSearch[0]`，或者你重新获取一遍完整的cookie试试

ok了正常跑了
