### ISSUE TITLE
任务做了积分不加

### ISSUE THREAD

**Issue by Jessire** [emtry/Bing-Auto-Search#20]
![image](https://user-images.githubusercontent.com/61305123/215779246-87c91f74-8490-4068-9035-d40fc4b344e8.png)

**Comment by emtry** [comment]
环境变量 isCN=1

**Comment by Jessire** [comment]
大佬能具体点吗，环境变量加了没用
<img width="689" alt="image" src="https://user-images.githubusercontent.com/61305123/216269318-40dd7851-c889-4331-b5c4-ac55828e9c44.png">

**Comment by emtry** [comment]
> 大佬能具体点吗，环境变量加了没用
> <img alt="image" width="1107" src="https://user-images.githubusercontent.com/61305123/216269557-bda42c37-2108-4e4e-ae76-446bff9019b6.png">

BingAutoSearch_isCN

**Comment by Jessire** [comment]
> > 大佬能具体点吗，环境变量加了没用
> > <img alt="image" width="1107" src="https://user-images.githubusercontent.com/61305123/216269557-bda42c37-2108-4e4e-ae76-446bff9019b6.png">
> 
> BingAutoSearch_isCN

<img width="637" alt="image" src="https://user-images.githubusercontent.com/61305123/216275963-b0881b36-29dd-40ba-a78d-90cddffb21f1.png">
![image](https://user-images.githubusercontent.com/61305123/216275979-4f7609d0-794d-4b03-9673-3d5e2c9b02a7.png)
感谢大佬的回复，但添加了还是没用

**Comment by emtry** [comment]
修改为UA环境变量为自己的UA
再不行可能是cookie问题吧
