### ISSUE TITLE
青龙/本地部署集成代理

### ISSUE THREAD

**Issue by Wittoy** [emtry/Bing-Auto-Search#3]
因为Microsoft Rewards区域问题，本地或者青龙面板需要其他地区代理方可完成Rewards日常搜索。能否在此基础上添加Socks5/Http代理

**Comment by oldye2020** [comment]
加一，能不能添加代理，让国内服务器也能跑

**Comment by emtry** [comment]
const HttpsProxyAgent = require("https-proxy-agent");

const httpsAgent = new HttpsProxyAgent(`http://127.0.0.1:7890`);
const axios_bing = axios.create({
    baseURL: 'https://www.bing.com/',
    timeout: 0,
    headers: {
        "Cookie": Cookie
    },
    withCredentials: true,
    proxy:false,
    httpsAgent
});

**Comment by emtry** [comment]
已更新2.0.4，支持HTTP proxy
