### ISSUE TITLE
一直显示未登录

### ISSUE THREAD

**Issue by Emily-0616** [emtry/Bing-Auto-Search#7]
试过在浏览器试过输入 document.cookie ，也试过在控制台doc 下rewards.bing.com 中的cookie。都是输出未登录。

**Comment by lovemybabyxuan** [comment]
对的,无论如何尝试,都是未登录,放弃了

**Comment by emtry** [comment]
bing.com 加上 rewards.bing.com 两个cookie就可以了，中间加个分号
