### ISSUE TITLE
无法在隐身窗口获取bing cookie

### ISSUE THREAD

**Issue by Plus-xu** [emtry/Bing-Auto-Search#9]
打开隐身窗口，登录bing，右上角不显示登录状态，获取的cookie无法使用，即使在微软网页登录以后也不显示，reward页面可以正常获取cookie。
非隐身状态可正常获取可用cookie
怎么才能隐身状态获取bing.com的cookie呢？

**Comment by emtry** [comment]
经测试，edge和Safari都可以获取到

**Comment by Juijote** [comment]
edge 是不行的，无痕模式下会自动禁用 bing 的登录功能；
